SELECT ED.ID AS ID, IFNULL(T.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN 
(SELECT PARENT_ID, COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID) T 
ON ED.ID = T.PARENT_ID
ORDER BY ID;


