SELECT CONCAT(T.QUARTER, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA O
JOIN
(SELECT ID,
CASE
    WHEN 
        MONTH(DIFFERENTIATION_DATE) >= 10
    THEN
        '4'
    WHEN
        MONTH(DIFFERENTIATION_DATE) >= 7
    THEN
        '3'
    WHEN
        MONTH(DIFFERENTIATION_DATE) >= 4
    THEN
        '2'
    ELSE
        '1'
END AS QUARTER
FROM ECOLI_DATA) T ON O.ID = T.ID 
GROUP BY T.QUARTER
ORDER BY T.QUARTER;

