-- 코드를 입력하세요
SELECT h.HISTORY_ID, 
CASE
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90%')
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30%') 
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN (SELECT (100 - REPLACE(DISCOUNT_RATE, '%', '')) / 100 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7%') 
    ELSE 1
END * c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;