SELECT HD.DEPT_ID AS DEPT_ID, HD.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT HD, HR_EMPLOYEES HE
WHERE HD.DEPT_ID = HE.DEPT_ID
GROUP BY HD.DEPT_ID
ORDER BY AVG_SAL DESC;